# Generated by Django 5.2.5 on 2025-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Client's first name.", max_length=100)),
                ('last_name', models.CharField(help_text="Client's last name.", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Client's email address (optional, but recommended for communication).", max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Client's phone number for contact.", max_length=20)),
                ('address', models.TextField(blank=True, help_text='Full address of the client.')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the client (e.g., preferences).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the client profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last date and time when the client profile was updated.')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
