# Generated by Django 5.2.5 on 2025-08-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A brief title for the task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the work to be done.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the task.', max_length=20)),
                ('deadline', models.DateField(blank=True, help_text='The date by which the task should be completed.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the task was marked as completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last date and time when the task was updated.')),
                ('client', models.ForeignKey(help_text='The client associated with this task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='clients.client')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
